[build-system]
requires = ["setuptools>=64.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "custom_mwclient"
dynamic = ["version"]
dependencies = [
    "mwclient~=0.10",
    "requests~=2.28",
]
requires-python = ">=3.9"

[tool.setuptools.dynamic]
version = {file = "version.txt"}
