from custom_mwclient.wiki_authentication import WikiAuth, WikiggAuth
from custom_mwclient.wiki_client import WikiClient
from custom_mwclient.clients.wikigg_client import WikiggClient
from custom_mwclient.clients.fandom_client import FandomClient
